<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #2d2d2d;
            margin: 0;
            padding: 0;
        }

        .report-header {
            background: #1f3a5f;
            padding: 20px 24px;
        }

        .header-table {
            width: 100%;
            border-collapse: collapse;
        }

        .brand-name {
            font-size: 15px;
            font-weight: bold;
            color: #C9A84C;
            letter-spacing: 1px;
        }

        .brand-sub {
            font-size: 10px;
            color: #94a3b8;
            margin-top: 2px;
        }

        .report-type-label {
            font-size: 16px;
            font-weight: bold;
            color: #C9A84C;
        }

        .report-date-label {
            font-size: 10px;
            color: #94a3b8;
            margin-top: 4px;
        }

        .accent-bar {
            background: #C9A84C;
            height: 4px;
            width: 100%;
        }

        .meta-strip {
            background: #f8f6f0;
            border: 1px solid #e8dfc8;
            border-radius: 6px;
            padding: 12px 16px;
            margin: 20px 0 24px;
        }

        .meta-strip table {
            width: 100%;
            border-collapse: collapse;
            margin: 0;
        }

        .meta-strip td {
            padding: 3px 8px 3px 0;
            border: none;
            font-size: 12px;
            color: #4b5563;
        }

        .meta-label {
            font-weight: bold;
            color: #1f3a5f;
            width: 100px;
        }

        h2 {
            font-size: 13px;
            font-weight: bold;
            color: #1f3a5f;
            text-transform: uppercase;
            letter-spacing: 0.8px;
            margin-top: 24px;
            margin-bottom: 8px;
            padding-bottom: 6px;
            border-bottom: 2px solid #C9A84C;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 6px;
        }

        th {
            background: #1f3a5f;
            color: #C9A84C;
            padding: 9px 12px;
            text-align: left;
            font-size: 11px;
            letter-spacing: 0.5px;
            text-transform: uppercase;
        }

        td {
            padding: 8px 12px;
            border-bottom: 1px solid #f0ebe0;
            font-size: 12px;
            color: #374151;
        }

        tbody tr:nth-child(even) td {
            background: #fdf9f2;
        }

        .total-row td {
            font-weight: bold;
            background: #f8f3e6;
            color: #1f3a5f;
            border-top: 2px solid #C9A84C;
            border-bottom: 2px solid #C9A84C;
        }

        .right {
            text-align: right;
        }

        .footer-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 40px;
            border-top: 1px solid #e8dfc8;
            padding-top: 10px;
        }

        .footer-left {
            font-size: 10px;
            color: #9ca3af;
        }

        .footer-right {
            font-size: 10px;
            color: #9ca3af;
            text-align: right;
        }

        .gold {
            color: #C9A84C;
        }
    </style>
</head>

<body>

    <div class="report-header">
        <table class="header-table">
            <tr>
                <td style="width:64px; vertical-align:middle;">
                    <img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('images/swahililogo.png'))) }}"
                        width="54" height="54" style="border-radius:6px;" />
                </td>
                <td style="vertical-align:middle; padding-left:10px;">
                    <div class="brand-name">SUMS</div>
                    <div class="brand-sub">Swahili Units Management System</div>
                </td>
                <td style="text-align:right; vertical-align:middle;">
                    <div class="report-type-label">COMPANY EXPENSE REPORT</div>
                    <div class="report-date-label">Generated {{ now()->format('d M Y') }}</div>
                </td>
            </tr>
        </table>
    </div>

    <div class="accent-bar"></div>

    <div class="meta-strip">
        <table>
            <tr>
                <td class="meta-label">Period</td>
                <td>{{ $label }}</td>
                <td class="meta-label">Total Expenses</td>
                <td><strong>TSh {{ number_format($total, 2) }}</strong></td>
            </tr>
            <tr>
                <td class="meta-label">Generated By</td>
                <td>{{ auth()->user()->name }}</td>
                <td class="meta-label">Date</td>
                <td>{{ now()->format('d M Y, H:i') }}</td>
            </tr>
        </table>
    </div>

    <h2>Expense Summary by Category</h2>
    <table>
        <tr>
            <th>Category</th>
            <th class="right">Total (TSh)</th>
        </tr>
        @foreach ($byCategory as $cat => $amount)
            <tr>
                <td>{{ $cat }}</td>
                <td class="right">{{ number_format($amount, 2) }}</td>
            </tr>
        @endforeach
        <tr class="total-row">
            <td>Grand Total</td>
            <td class="right">{{ number_format($total, 2) }}</td>
        </tr>
    </table>

    <h2>Detailed Expense Listing</h2>
    <table>
        <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Category</th>
            <th class="right">Amount (TSh)</th>
        </tr>
        @foreach ($expenses as $expense)
            <tr>
                <td>{{ $expense->date->format('d M Y') }}</td>
                <td>{{ $expense->title }}</td>
                <td>{{ $expense->category }}</td>
                <td class="right">{{ number_format($expense->amount, 2) }}</td>
            </tr>
        @endforeach
        <tr class="total-row">
            <td colspan="3">Total</td>
            <td class="right">{{ number_format($total, 2) }}</td>
        </tr>
    </table>

    <table class="footer-table">
        <tr>
            <td class="footer-left">
                SUMS — Swahili Units Management System &nbsp;·&nbsp;
                <span class="gold">Confidential</span>
            </td>
            <td class="footer-right">{{ now()->format('d M Y, H:i') }}</td>
        </tr>
    </table>

</body>

</html>
